import type { Metadata } from "next";
import MySidebar from "@/components/MySidebar";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-primary",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Cesk.",
  description: "Generated by Cesar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${outfit.variable} antialiased`}>
        <MySidebar />
        <main className="relative min-h-screen">{children}</main>
      </body>
    </html>
  );
}
